# -*- coding: utf-8 -*-
"""advertisingF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zocp4G7uv68LIazs1u97MxbDSPUDX0Bz
"""

try:
  import streamlit as st
except ModuleNotFoundError:
  import os
  os.system("pip install streamlit")
  import streamlit as st

import pandas as pd
import plotly.express as px

df=pd.read_csv('Advertising_F.csv')
df.head()

st.title("Advertising Effectiveness Dashboard")
st.sidebar.header("filters")
x_var=st.sidebar.selectbox("X-Axis",['TV','radio','newspaper'])
y_var=st.sidebar.selectbox("Y-Axis",['sales'])

fig=px.scatter(df,x=x_var,y=y_var,trendline='ols')
st.plotly_chart(fig)

st.write('### Data Frame' )
st.dataframe(df)

st.title("Its a map!!!")

fig=px.scatter_mapbox(df,lat='latitude',lon='longitude',color='sales',size='TV',hover_name='City',zoom=3)
fig.update_layout(mapbox_style="carto-positron")
st.plotly_chart(fig)
