# -*- coding: utf-8 -*-
"""advertise.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eczLAAgn1mPjQJHTgM5ud8pWoAULRkl0
"""

!pip install streamlit

import pandas as pd

url = "https://raw.githubusercontent.com/selva86/datasets/master/Advertising.csv"
df = pd.read_csv(url)
df.to_csv("Advertising.csv", index=False)
df.head()

import streamlit as st
import pandas as pd
import plotly.express as px

# Load data
df = pd.read_csv("Advertising.csv")

st.title("📊 Advertising Effectiveness Dashboard")

st.sidebar.header("Filters")
x_var = st.sidebar.selectbox("X-Axis", df.columns[:-1])
y_var = st.sidebar.selectbox("Y-Axis", [df.columns[-1]])

fig = px.scatter(df, x=x_var, y=y_var, trendline="ols",
                 title=f"{y_var} vs {x_var}")
st.plotly_chart(fig, use_container_width=True)

st.write("### Data Preview")
st.dataframe(df.head())